#!/usr/bin/env python3
"""Render private deployment configuration. Existing credentials are never rotated."""
import argparse
import json
import os
from pathlib import Path
import re
import secrets

HOST = re.compile(r"(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$")
NAME = re.compile(r"[A-Za-z0-9_-]{1,80}$")

def write_private(path, text):
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, 'w') as out:
        out.write(text)
    path.chmod(0o600)


def render(site, output):
    for field in ('casdoor_host', 'headscale_host', 'headplane_host', 'tailnet_domain'):
        if not HOST.fullmatch(site.get(field, '')):
            raise ValueError(f'{field} must be a DNS hostname without scheme or path')
    for field in ('organization', 'headscale_client_id', 'headplane_client_id', 'admission_group'):
        if not NAME.fullmatch(site.get(field, '')):
            raise ValueError(f'{field} must be a simple identifier')
    if len({site[x] for x in ('casdoor_host', 'headscale_host', 'headplane_host', 'tailnet_domain')}) != 4:
        raise ValueError('Service hostnames and tailnet DNS suffix must be distinct')
    inputs = json.loads((Path(__file__).resolve().parents[1] / 'image-inputs.json').read_text())
    if inputs.get('schema_version') != 1:
        raise ValueError('Unsupported image input schema')
    output = Path(output).resolve()
    if any(c in str(output) for c in '\n\r$# '):
        raise ValueError('Runtime directory must not contain whitespace, dollar signs, or #')
    output.mkdir(parents=True, exist_ok=True, mode=0o700)
    output.chmod(0o700)
    for directory in ('casdoor/logs', 'headscale/data', 'headplane/data', 'sync/state', 'secrets'):
        (output / directory).mkdir(parents=True, exist_ok=True, mode=0o700)
    for name in ('db_password', 'headscale_oidc_secret', 'headplane_oidc_secret', 'cookie_secret'):
        path = output / 'secrets' / name
        if not path.exists():
            write_private(path, secrets.token_hex(16 if name == 'cookie_secret' else 32))
    db_password = (output / 'secrets/db_password').read_text().strip()
    if not re.fullmatch(r'[a-f0-9]{64}', db_password):
        raise ValueError('Generated database password must remain a 64-character hex value')
    # Keep API key absent until generated by the running Headscale instance.
    issuer = 'https://' + site['casdoor_host']
    write_private(output / 'casdoor/app.conf', f'''appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = postgres
dataSourceName = "user=casdoor password={db_password} host=db port=5432 sslmode=disable dbname=casdoor"
dbName = casdoor
showSql = false
origin = {issuer}
originFrontend = {issuer}
isDemoMode = false
initDataNewOnly = true
logPostOnly = true
frontendBaseDir = "./web/build"
''')
    hs = {
        'server_url': 'https://' + site['headscale_host'],
        'listen_addr': '0.0.0.0:8080', 'metrics_listen_addr': '0.0.0.0:9090',
        'noise': {'private_key_path': '/var/lib/headscale/noise_private.key'},
        'prefixes': {'v4': '100.64.0.0/10', 'v6': 'fd7a:115c:a1e0::/48', 'allocation': 'sequential'},
        'database': {'type': 'sqlite', 'sqlite': {'path': '/var/lib/headscale/db.sqlite', 'write_ahead_log': True}},
        'node': {'expiry': '30d'},
        'dns': {'magic_dns': True, 'base_domain': site['tailnet_domain'], 'nameservers': {'global': ['1.1.1.1', '8.8.8.8']}},
        'derp': {'server': {'enabled': False}, 'urls': ['https://controlplane.tailscale.com/derpmap/default'], 'auto_update_enabled': True, 'update_frequency': '3h'},
        'policy': {'mode': 'file', 'path': '/etc/headscale/policy.json'},
        'unix_socket': '/var/lib/headscale/headscale.sock', 'unix_socket_permission': '0770',
        'oidc': {'issuer': issuer, 'client_id': site['headscale_client_id'], 'client_secret_path': '/run/secrets/oidc_secret',
                 'only_start_if_oidc_is_available': True, 'scope': ['openid', 'profile', 'email', 'groups'],
                 'allowed_groups': [site['organization'] + '/' + site['admission_group']],
                 'email_verified_required': True, 'use_expiry_from_token': False, 'pkce': {'enabled': True, 'method': 'S256'}}
    }
    hp = {
        'server': {'host': '0.0.0.0', 'port': 3000, 'base_url': 'https://' + site['headplane_host'],
                   'cookie_secret_path': '/run/secrets/cookie_secret', 'cookie_secure': True, 'cookie_max_age': 300},
        'headscale': {'url': 'http://headscale:8080', 'public_url': 'https://' + site['headscale_host'], 'api_key_path': '/run/secrets/headscale_api_key'},
        'oidc': {'issuer': issuer, 'client_id': site['headplane_client_id'], 'client_secret_path': '/run/secrets/oidc_secret',
                 'use_pkce': True, 'disable_api_key_login': True, 'scope': 'openid email profile groups',
                 'default_role': 'member', 'role_claim': 'headplane_role', 'allow_weak_rsa_keys': False}
    }
    # JSON is a strict subset of YAML; retain YAML filenames expected by both apps.
    for filename, config in (('headscale/config.yaml', hs), ('headplane/config.yaml', hp)):
        write_private(output / filename, json.dumps(config, indent=2) + '\n')
    policy = output / 'headscale/policy.json'
    if not policy.exists():
        write_private(policy, json.dumps({'groups': {}, 'acls': []}, indent=2) + '\n')
    env = {
        'COMPOSE_PROJECT_NAME': 'integrated-tailnet', 'RUNTIME_DIR': str(output), 'RUN_UID': str(os.getuid()), 'RUN_GID': str(os.getgid()),
        'CASDOOR_HOST': site['casdoor_host'], 'HEADSCALE_HOST': site['headscale_host'], 'HEADPLANE_HOST': site['headplane_host'],
        'HEADSCALE_IMAGE': 'tailnet/headscale:2026.09-rc.1', 'HEADPLANE_IMAGE': 'tailnet/headplane:2026.09-rc.1',
        'CASDOOR_IMAGE': 'tailnet/casdoor:2026.09-rc.1', 'POSTGRES_IMAGE': inputs['images']['database'],
        'CADDY_IMAGE': inputs['images']['reverse_proxy'], 'WORKER_IMAGE': inputs['images']['sync']
    }
    # Preserve operator image digest pins on rerender.
    env_path = output / 'compose.env'
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            key, sep, value = line.partition('=')
            if sep and key in env and (key.endswith('_IMAGE') or key == 'COMPOSE_PROJECT_NAME'):
                env[key] = value
    write_private(env_path, ''.join(f'{key}={value}\n' for key, value in env.items()))
    return output

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--site', required=True, type=Path)
    parser.add_argument('--output', default='.runtime', type=Path)
    args = parser.parse_args()
    try:
        render(json.loads(args.site.read_text()), args.output)
    except (ValueError, OSError) as error:
        parser.exit(1, f'Configuration failed: {error}\n')
    print('Private configuration generated; existing secrets, image pins and policy preserved.')
